---
- name: Install node and npm
  hosts: 165.232.127.190
  tasks: 
    - name: Update apt repository and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm


- name: Create new Linux User for nodejs application
  hosts: 165.232.127.190
  vars_files:
    - app_deploy_vars
  tasks: 
    - name: Create linux user
      user:
        name: "{{linux_username}}"
        comment: node application user
        group: admin
      register: user_creation
    - debug: msg={{user_creation.name}}
    


- name: Deploy nodejs app
  hosts: 165.232.127.190
  vars_files:
    - app_deploy_vars
  become: True
  become_user: "{{linux_username}}"
  tasks:  
    - name: Copy and Unpack the nodejs file 
      unarchive: 
        src: "{{location}}nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
    - name: Install dependencies
      npm:
        path: "{{destination}}/package"
    - name: Start the application
      command: 
        chdir: "{{destination}}/package/app/"
        cmd: node server.js
      async: 1000
      poll: 0
    - name: Ensure the application is running
      shell: ps aux | grep node 
      register: process_status
    - debug: msg={{process_status.stdout_lines}}
