---
- name: Install node and npm
  hosts: 165.232.127.190
  tasks: 
    - name: Update apt repository and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm


- name: Create new Linux User for nodejs application
  hosts: 165.232.127.190
  tasks: 
    - name: Create linux user
      user:
        name: app_user
        comment: node application user
        group: admin
      register: user_creation
    - debug: msg={{user_creation}}
    


- name: Deploy nodejs app
  hosts: 165.232.127.190
  become: True
  become_user: app_user
  tasks:  
    - name: Copy and Unpack the nodejs file 
      unarchive: 
        src: /work/proj/devops_bootcamp/15_DevOps_Ansible/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /home/app_user 
    - name: Install dependencies
      npm:
        path: /home/app_user/package
    - name: Start the application
      command: 
        chdir: /home/app_user/package/app/
        cmd: node server.js
      async: 1000
      poll: 0
    - name: Ensure the application is running
      shell: ps aux | grep node 
      register: process_status
    - debug: msg={{process_status.stdout_lines}}
