---
- name: Install node and npm
  hosts: 165.232.127.190
  tasks: 
    - name: Update apt repository and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
- name: Deploy nodejs app
  hosts: 165.232.127.190
  tasks:  
    - name: Copy and Unpack the nodejs file 
      unarchive: 
        src: /work/proj/devops_bootcamp/15_DevOps_Ansible/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /root/ 
