---
- name: Make sure the docker is running
  hosts: docker_server
  vars_files:
    - project-vars
  become: yes
  tasks:
    - name: Install docker
      yum: 
        name: docker
        state: present
        update_cache: yes
    - name: Creates user and adds user to docker group
      user:
        name: "{{linux_user}}"
        groups: [docker]
    - name: Reset SSH connection
      meta: reset_connection

    - name: Start docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      register: service_status
    - debug: msg="{{service_status.state}}"

- name: Make docker-compose available
  hosts: docker_server
  vars_files:
    - project-vars
  tasks:
    - name: Create cli plugin directory
      file: 
        path: "{{ec2_home}}/.docker/cli-plugins"
        state: directory
    - name: Get operating system info
      command: uname -s
      register: linux_os
    - name: Get architecture
      command: uname -m
      register: linux_arch   
    - name: Download docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{linux_os.stdout | lower}}-{{linux_arch.stdout}}"
        dest: "{{ec2_home}}/.docker/cli-plugins/docker-compose"
    - name: Add executable permisson to docker-compose
      file:
        path: "{{ec2_home}}/.docker/cli-plugins/docker-compose"
        mode: +x
    - name: check the docker compose version
      command: docker compose version
      register: compose_version
    - debug: msg="{{compose_version.stdout}}"

- name: Run docker images by docker compose
  hosts: docker_server  
  vars_prompt:
    - name: dockerhub_password
      prompt: "Enter your DockerHub password for user petrdeveloper"
      private: yes
  vars_files:
    - project-vars
  tasks:
    - name: Copy Docker Compose File to sever
      copy:
        src: docker-compose-full.yaml
        dest: "{{ec2_home}}/docker-compose.yaml"
    - name: Docker Login
      community.docker.docker_login:
        username: petrdeveloper
        password: "{{dockerhub_password}}"
    - name: Run docker compose
      community.docker.docker_compose_v2: 
        project_src: "{{ec2_home}}"
        files:
          - docker-compose.yaml
        state: present
